server:
  port: 10139
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.jinxin.platform.**.domain #待实现通配符方式
  mapper-locations: classpath*:**/xml/*Mapper.xml

platform:
  upload: D:\testdata

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.60.226:1521:oracl
    username: platform
    password: platform
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: yang
    timeout: 60000
    lettuce:
      pool:
        max-active: 2000
        max-idle: 500
        min-idle: 200
        max-wait: 60000
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  devtools:
    restart:
      enabled: true
#日志配置
logging:
  level:
    com.jinxin: debug
    org.springframework: warn
    org.apache.ibatis.logging: debug
